@host = http://localhost:
@port = 3000


### Usuarios API ###
GET {{host}}{{port}}/api/usuarios

### insertar un nuevo usuario
POST {{host}}{{port}}/api/usuarios/register
Content-Type: application/json

{
    "nombre": "xuvi",
    "email": "xuvito@gmail.com",
    "password": "13456"
}

### comprobar si un email ya está registrado
GET {{host}}{{port}}/api/usuarios/check-email?email=tres@gmail.com

### logar un usuario existente
POST {{host}}{{port}}/api/usuarios/login
Content-Type: application/json

{
    "nombre": "xuvi",
    "email": "xuvito@gmail.com",
    "password": "13456"
}

### Editar un usuario existente
PUT {{host}}{{port}}/api/usuarios/1
Content-Type: application/json

{
    "nombre": "mari",
    "email": "mari@gmail.com",
    "password": "123456"
}

### borrar un usuario existente
DELETE {{host}}{{port}}/api/usuarios/13



### Viajes API ###
### ver todos los viajes
GET {{host}}{{port}}/api/viajes


### ver viaje by id
GET {{host}}{{port}}/api/viajes/3



### Peticiones API ###

### Obtener comentarios
GET {{host}}{{port}}/api/comentarios/1


### Crear comentario
POST {{host}}{{port}}/api/comentarios/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTc0NDg3NzE0MH0.rV1vytQPAe3Xi7u3J1Ro4LuPnvaURKGLsvq8cL-j8W8


{
  "usuarios_id_usuario": 3,
  "comentario": "¡Una experiencia espectacular!"
}


### Reviews API ###

GET http://localhost:3000/api/reviews/viaje/1

### Obtener todas las reviews
GET {{host}}{{port}}/api/reviews

### Obtener reviews de un viaje específico (ej. viaje con id 1)
GET {{host}}{{port}}/api/reviews/viaje/1


###
GET http://localhost:3000/api/reviews/viaje/1/usuario
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImlhdCI6MTc0NTA3MTk5MH0.Zhvd7n2wCbfi5ecNgSajV66qaikIkrDy1BSp8pNq9b0

### Crear una nueva review
POST {{host}}{{port}}/api/reviews
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImlhdCI6MTc0NTA3MTk5MH0.Zhvd7n2wCbfi5ecNgSajV66qaikIkrDy1BSp8pNq9b0

{
  "usuarios_id_usuario": 18,
  "viajes_id_viaje": 1,
  "puntuacion": 3,
  "review": "Vaya viaje de mierda",
  "fecha": "2025-04-19"
}

### Actualizar una review (ej. id 2)
PUT {{host}}{{port}}/api/reviews/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImlhdCI6MTc0NTA3MTk5MH0.Zhvd7n2wCbfi5ecNgSajV66qaikIkrDy1BSp8pNq9b0

{
  "puntuacion": 4,
  "review": "Muy bueno, aunque podría mejorar en algunos aspectos.",
  "fecha": "2025-04-19"
}

### Eliminar una review (ej. id 2)
DELETE {{host}}{{port}}/api/reviews/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImlhdCI6MTc0NTA3MTk5MH0.Zhvd7n2wCbfi5ecNgSajV66qaikIkrDy1BSp8pNq9b0
