@host = http://localhost:
@port = 3000

###
GET {{host}}{{port}}/api/usuarios 

###
PUT {{host}}{{port}}/api/usuarios/1
Content-Type: application/json

{
    "nombre": "juan",
    "email": "juan@gmail.com" ,
    "password": "123456",
    "fecha_registro": "2023-10-01"
}

###
POST {{host}}{{port}}/api/usuarios
Content-Type: application/json

{
    "nombre": "Ruben",
    "email": "rubencito@gmail.com",
    "password": 45678,
    "fecha_registro": "2025-04-11"

}

###
DELETE {{host}}{{port}}/api/usuarios/1
