@host = http://localhost:
@port = 3000

### Usuarios API ###
GET {{host}}{{port}}/api/usuarios

### insertar un nuevo usuario
POST {{host}}{{port}}/api/usuarios/register
Content-Type: application/json

{
    "nombre": "chipi",
    "email": "chipi@gmail.com",
    "password": "13456"
}

### comprobar si un email ya está registrado
GET {{host}}{{port}}/api/usuarios/check-email?email=tres@gmail.com

### logar un usuario existente
POST {{host}}{{port}}/api/usuarios/login
Content-Type: application/json

{
    "nombre": "chipi",
    "email": "chipi@gmail.com",
    "password": "13456"
}

### Editar un usuario existente
PUT {{host}}{{port}}/api/usuarios/1
Content-Type: application/json

{
    "nombre": "mari",
    "email": "mari@gmail.com",
    "password": "123456"
}

### borrar un usuario existente
DELETE {{host}}{{port}}/api/usuarios/13

### Viajes API ###
### ver todos los viajes
GET {{host}}{{port}}/api/viajes


### Obtener comentarios
GET {{host}}{{port}}/api/comentarios/1


### Crear comentario
POST http://localhost:3000/api/comentarios/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTc0NDg3NzE0MH0.rV1vytQPAe3Xi7u3J1Ro4LuPnvaURKGLsvq8cL-j8W8


{
  "usuarios_id_usuario": 3,
  "comentario": "¡Una experiencia espectacular!"
}